name    'erwbgy-tomcat'
version '0.6.5'
source 'https://github.com/erwbgy/puppet-tomcat.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Run Tomcat instances under Runit'
description 'Run Tomcat instances under Runit'
project_page 'https://github.com/erwbgy/puppet-tomcat'
dependency 'erwbgy/runit', '>= 0.4.2'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
